# COMPUTER VISION
## Project: Detect the chess board

group 14
- Pedro Azevedo, up 201905955
- Santiago Pineda up 202403071
- 
- Michal kowalski up 202401554

### Install requirements

In [ ]:
! pip install -r requirements.txt

## prepare the image

In [3]:
import cv2
import numpy as np
import os
from src.src import *


# Path to directory with images
dataDir = os.path.join(".","images", '42')
auxiliaryDir = os.path.join("images", 'auxiliary_data')

In [4]:
# Open testing image
img_path = [os.path.join(dataDir, 'G042_IMG000.jpg')]
print("hi", img_path)
# Read image
imgs, gray_imgs, img_names = read_images(img_path)
print("hi")
# Show image
show_imags(imgs, img_names)
show_imags(gray_imgs, img_names)

hi ['.\\images\\42\\G042_IMG000.jpg']
hi


In [23]:
ret, corners = cv2.findChessboardCornersSB(imgs[0], (7,7), None)
print(corners)

[[[1351.8352 1165.5884]]

 [[1494.5952 1220.1064]]

 [[1639.7709 1274.145 ]]

 [[1787.9015 1327.5905]]

 [[1939.9341 1388.2937]]

 [[2096.431  1448.4077]]

 [[2256.7808 1509.1827]]

 [[1280.6589 1295.581 ]]

 [[1425.2246 1352.6926]]

 [[1571.867  1409.0322]]

 [[1721.2777 1464.8938]]

 [[1874.7166 1528.0142]]

 [[2033.2668 1591.1254]]

 [[2195.9473 1654.7836]]

 [[1206.971  1429.5343]]

 [[1353.2695 1488.8643]]

 [[1501.7563 1547.7631]]

 [[1652.7014 1606.3673]]

 [[1808.0254 1672.469 ]]

 [[1968.3848 1738.4281]]

 [[2133.3665 1805.4183]]

 [[1129.8411 1568.121 ]]

 [[1278.696  1629.8988]]

 [[1428.9352 1691.6732]]

 [[1581.28   1752.6188]]

 [[1739.3826 1822.1536]]

 [[1901.7634 1891.515 ]]

 [[2068.5989 1961.5957]]

 [[1049.6405 1712.1553]]

 [[1200.3148 1776.7589]]

 [[1353.3733 1841.5676]]

 [[1507.0131 1906.3699]]

 [[1668.3522 1978.2855]]

 [[1832.8007 2050.9153]]

 [[2001.5402 2124.0803]]

 [[ 966.5038 1862.2653]]

 [[1119.0297 1929.798 ]]

 [[1273.9491 1997.9806]]

 [[1431.4786

In [25]:
img = imgs[0]
img = cv2.resize(img, (640, 480))

ret, corners = cv2.findChessboardCornersSB(img, (7,7), None)

print(corners)

None


In [28]:
img = imgs[0]
original_height, original_width = img.shape[:2]
resized_width, resized_height = 640, 480

ret, corners = cv2.findChessboardCornersSB(img, (7,7), None)

img_rersize = cv2.resize(img, (resized_width, resized_height))

if True:
   objpoints.append(objp)
   
   # Scale the corner coordinates
   scale_x = resized_width / original_width
   scale_y = resized_height / original_height
   scaled_corners = corners * np.array([[[scale_x, scale_y]]], dtype=np.float32)
   
   # Draw and display the corners
   fnl = cv2.drawChessboardCorners(img_rersize, (7,7), scaled_corners, ret)
   
   show_imags([fnl])

cv2.destroyAllWindows()

In [5]:
import glob

image_paths = []
pattern = os.path.join(dataDir, '*.jpg')
image_paths.extend(glob.glob(pattern))

imgs, gray_imgs, img_names = read_images(image_paths)

ret, corners = detect_chessboard_corners(imgs, img_names, 640, 480)

Image G042_IMG000 has corners
Image G042_IMG001 does not have corners
Image G042_IMG002 does not have corners
Image G042_IMG003 does not have corners
Image G042_IMG004 does not have corners
Image G042_IMG005 does not have corners
Image G042_IMG006 does not have corners
Image G042_IMG007 does not have corners
Image G042_IMG008 does not have corners
Image G042_IMG009 does not have corners
Image G042_IMG010 does not have corners
Image G042_IMG011 does not have corners
Image G042_IMG012 does not have corners
Image G042_IMG013 does not have corners
Image G042_IMG014 does not have corners
Image G042_IMG015 has corners
Image G042_IMG016 does not have corners
Image G042_IMG017 does not have corners
Image G042_IMG018 does not have corners
Image G042_IMG019 has corners
Image G042_IMG020 does not have corners
Image G042_IMG021 does not have corners
Image G042_IMG022 does not have corners
Image G042_IMG023 does not have corners
Image G042_IMG024 does not have corners
Image G042_IMG025 does not hav

In [3]:
import glob

image_paths = []
pattern = os.path.join(dataDir, '*.jpg')
image_paths.extend(glob.glob(pattern))

imgs, gray_imgs, img_names = read_images(image_paths)

show_imags(imgs, img_names)
